name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Lint
        run: |
          source .venv/bin/activate
          ruff check .
          black --check .
      - name: Test
        run: |
          source .venv/bin/activate
          pytest -q
